micronaut:
  application:
    name: randomNumberGen
  metrics:
    export:
      prometheus:
        enabled: true
        descriptions: true
        step: PT1M
    enabled: true
  health:
    enabled: true
    sensitive: false
    url:
      enabled: true

#kafka.bootstrap.servers: localhost:9092
kafka:
  bootstrap:
    #servers: host.docker.internal:9092
    servers: localhost:9092

kubernetes:
  client:
    namespace: dev
